# Generated by Django 5.0 on 2025-01-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0003_paidcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('video', 'Video'), ('word', 'Word Document')], max_length=50)),
                ('resource_file', models.FileField(upload_to='course_resources/')),
            ],
        ),
    ]
