# Generated by Django 5.0 on 2025-01-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
