# Generated by Django 5.0 on 2025-02-06 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0003_courseprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprogress',
            name='completed_contents',
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='content',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='lmsapp.coursecontent'),
        ),
    ]
