# Generated by Django 5.0 on 2025-01-14 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0006_subadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subadmin',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='subadmin',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='subadmin',
            name='username',
        ),
    ]
