# Generated by Django 5.0 on 2025-04-01 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0007_remove_freecourse_youtube_link_coursechapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mobile',
        ),
    ]
