# Generated by Django 5.0 on 2025-06-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0013_alter_customuser_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='module',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paidcourse',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paidcourse',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paidcourse',
            name='testimonials',
            field=models.TextField(blank=True, null=True),
        ),
    ]
