# Generated by Django 5.0 on 2025-06-16 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0014_coursecontent_module_paidcourse_about_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontent',
            name='module',
        ),
    ]
