# Generated by Django 5.0 on 2025-06-17 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0016_remove_payment_first_name_remove_payment_timestamp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
