# Generated by Django 5.0 on 2025-06-18 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0018_newpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsapp.customuser'),
        ),
        migrations.AlterField(
            model_name='subadmin',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
