# Generated by Django 5.0 on 2025-06-18 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0020_usercourseaccess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCourseAccess',
        ),
    ]
