# Generated by Django 5.0 on 2025-06-18 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0022_usercourseaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourseaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsapp.customuser'),
        ),
    ]
