# Generated by Django 5.0 on 2025-06-18 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0023_alter_usercourseaccess_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourseaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
