# Generated by Django 5.0 on 2025-06-18 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0024_alter_usercourseaccess_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercourseaccess',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='usercourseaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsapp.customuser'),
        ),
    ]
