# Generated by Django 5.0 on 2025-06-18 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0025_alter_usercourseaccess_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCourseAccess',
        ),
    ]
