# Generated by Django 5.0 on 2025-06-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0027_usercourseaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
