# Generated by Django 5.0 on 2025-06-20 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0028_courseprogress_progress_percentage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseprogress',
            unique_together={('user', 'course')},
        ),
        migrations.RemoveField(
            model_name='courseprogress',
            name='content',
        ),
    ]
