# Generated by Django 5.0 on 2025-06-21 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0030_coursereview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursereview',
            unique_together=set(),
        ),
    ]
