# Generated by Django 5.0 on 2025-06-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0031_alter_coursereview_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidcourse',
            name='course_name',
            field=models.CharField(default='python', max_length=255),
        ),
    ]
