# Generated by Django 5.0 on 2025-06-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0032_paidcourse_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidcourse',
            name='course_code',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
