# Generated by Django 5.0 on 2025-06-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0033_paidcourse_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidcourse',
            name='course_code',
            field=models.CharField(default='pending', max_length=100, unique=True),
        ),
    ]
