# Generated by Django 5.0 on 2025-06-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0034_alter_paidcourse_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidcourse',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
