# Generated by Django 5.0 on 2025-06-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0035_paidcourse_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidcourse',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
