# Generated by Django 5.0 on 2025-06-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0037_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='is_admin_generated',
            field=models.BooleanField(default=False),
        ),
    ]
