# Generated by Django 5.0 on 2025-06-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0038_coursereview_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpayment',
            name='course_duration_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='usercourseaccess',
            name='expires_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
