# Generated by Django 5.0 on 2025-06-27 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0039_newpayment_course_duration_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpayment',
            name='course_duration_days',
        ),
        migrations.RemoveField(
            model_name='usercourseaccess',
            name='expires_on',
        ),
    ]
