# Generated by Django 5.0 on 2025-06-27 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0041_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
