# Generated by Django 5.0 on 2025-06-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0043_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
