# Generated by Django 5.0 on 2025-06-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0044_invoice_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_subadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='SubAdmin',
        ),
    ]
