# Generated by Django 5.0 on 2025-06-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0045_customuser_is_subadmin_delete_subadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='plain_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
