# Generated by Django 5.0 on 2025-06-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0048_customuser_is_subadmin_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
