# Generated by Django 5.0 on 2025-07-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0050_completedcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpayment',
            name='invoice_created',
            field=models.BooleanField(default=False),
        ),
    ]
