# Generated by Django 5.0 on 2025-07-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0052_remove_newpayment_invoice_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpayment',
            name='create_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
