# Generated by Django 5.0 on 2025-07-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0053_newpayment_create_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpayment',
            name='create_invoice',
            field=models.BooleanField(default=True),
        ),
    ]
