# Generated by Django 5.0 on 2025-07-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0054_alter_newpayment_create_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpayment',
            name='create_invoice',
        ),
        migrations.AddField(
            model_name='newpayment',
            name='invoice_created',
            field=models.BooleanField(default=False),
        ),
    ]
