# Generated by Django 5.0 on 2025-07-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0055_remove_newpayment_create_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpayment',
            name='canceled_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
