# Generated by Django 5.0 on 2025-07-09 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0056_newpayment_canceled_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpayment',
            name='canceled_invoice',
        ),
    ]
