# Generated by Django 5.0 on 2025-07-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0057_remove_newpayment_canceled_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpayment',
            name='canceled_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
