# Generated by Django 5.0 on 2025-07-14 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0059_revokedaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='revokedaccess',
            name='payment',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='lmsapp.newpayment'),
        ),
    ]
