# Generated by Django 5.0 on 2025-07-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0060_revokedaccess_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpayment',
            name='is_revoked',
            field=models.BooleanField(default=False),
        ),
    ]
