# Generated by Django 5.0 on 2025-07-18 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0061_newpayment_is_revoked'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='lmsapp.newpayment'),
        ),
    ]
