# Generated by Django 5.0 on 2025-07-21 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0065_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidcourse',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lmsapp.category'),
        ),
    ]
