# Generated by Django 5.0 on 2025-08-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0068_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_percent', models.PositiveIntegerField(help_text='Discount percentage (e.g. 10 for 10%)')),
                ('min_amount', models.DecimalField(decimal_places=2, help_text='Minimum cart amount to apply coupon', max_digits=10)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('courses', models.ManyToManyField(blank=True, help_text='Leave empty for all courses', to='lmsapp.paidcourse')),
            ],
        ),
    ]
