# Generated by Django 5.0 on 2025-08-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0070_newpayment_coupon_code_newpayment_discount_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpayment',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='newpayment',
            name='discount_percent',
        ),
    ]
