# Generated by Django 5.0 on 2025-08-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0071_remove_newpayment_coupon_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpayment',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newpayment',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
