# Generated by Django 5.0 on 2025-08-14 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0073_remove_newpayment_coupon_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpayment',
            name='applied_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lmsapp.coupon'),
        ),
        migrations.AddField(
            model_name='newpayment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
