# Generated by Django 5.0 on 2025-08-14 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0074_newpayment_applied_coupon_newpayment_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpayment',
            name='applied_coupon',
        ),
        migrations.RemoveField(
            model_name='newpayment',
            name='discount_amount',
        ),
    ]
