# Generated by Django 5.0 on 2025-08-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0076_newpayment_coupon_code_newpayment_discount_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='slider_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='slider_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='slider_images/')),
            ],
        ),
    ]
