# Generated by Django 5.0 on 2025-08-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0078_invoice_coupon_code_invoice_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='navbar_logo',
            field=models.ImageField(blank=True, default='default/navbar_default.png', null=True, upload_to='category_navbar/'),
        ),
    ]
