# Generated by Django 5.0 on 2026-03-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0079_category_navbar_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecontent',
            options={'ordering': ['title_order', 'id']},
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='title_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
