# Generated by Django 5.0 on 2026-03-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0080_alter_coursecontent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecontent',
            options={},
        ),
        migrations.RemoveField(
            model_name='coursecontent',
            name='title_order',
        ),
    ]
