# Generated by Django 5.0 on 2026-03-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0081_alter_coursecontent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
